version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000
    networks:
        - photos-web
    # Set environment variables based on the .env file
    env_file:
      - .env
      - ./next-app/.env.local
    volumes:
      - ./next-app/src:/app/src
      - uploads:/app/public/uploads

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  photos-web:
    external: true

volumes:
  uploads: